name: Semantic artefacts scripted integration for EarthPortal

on:
  schedule:
    # Runs every day at 4:30 PM UTC (approximates 5:30 PM CET)
    - cron: '30 16 * * *'
    
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Update GCMD
        run: |
          python scripts/concat_GCMD.py
          python scripts/concat_GCMD.py --all
      
      - name: Update NVS vocabularies
        run: |
          python3 scripts/nvs_updater.py --input semantic_artefacts/C17.ttl --url https://vocab.nerc.ac.uk/collection/C17/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/C19.ttl --url https://vocab.nerc.ac.uk/collection/C19/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/L06.ttl --url https://vocab.nerc.ac.uk/collection/L06/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/L22.ttl --url https://vocab.nerc.ac.uk/collection/L22/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/P02.ttl --url https://vocab.nerc.ac.uk/collection/P02/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/P07.ttl --url https://vocab.nerc.ac.uk/collection/P07/current/?_profile=nvs&_mediatype=text/turtle
          python3 scripts/nvs_updater.py --input semantic_artefacts/P06.ttl --url https://vocab.nerc.ac.uk/collection/P06/current/?_profile=nvs&_mediatype=text/turtle
          

      # Compare the output file and commit changes if different
      - name: Check if file has been updated and commit changes
        run: |
          sa_folder="semantic_artefacts"
          
          # Check if the original file has been updated by comparing it with the previously committed version
          git diff --quiet "$sa_folder" || {
            echo "Changes detected in $sa_folder, committing changes..."
            git config --global user.name "earthportal-sac"
            git config --global user.email "earthportal.sac@gmail.com"
            git add "$sa_folder/*"
            git commit -m "New version(s) of semantic artefact(s)"
            git push origin main
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
